Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -38,3 +38,9 @@ jobs:
       - name: Make Unit test report
         uses: doanpt/AndroidTestReportAction@v1.0
         if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
+
+      - name: Prevent merge on test failure
+        if: failure()
+        run: |
+          echo "Unit tests failed. Merging is not allowed."
+          exit 1
